app/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('medicos/', include('medico.urls')),
    path('paciente/', include('paciente.urls')),
    path('', lambda request: redirect('/usuarios/login/'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paciente/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name="url_home"),
    path('escolher_horario/<int:id_dados_medicos>/',
         views.fnctn_esclhr_hrrio, name="url_escler_hrrio"),
    path('agendar_horario/<int:id_data_aberta>/',
         views.fnctn_agndr_hrrio, name="url_agndr_horario"),
    path('minhas_consultas/', views.fnctn_mnhs_cnslts, name="url_mnhs_cnslts"),
    path('consulta/<int:id_consulta>/', views.fnctn_cnslta, name="url_cnslta"),
    path('consultas/', views.fnctn_pcnts_cnsltas, name="url_pcnts_cnsltas"),
    path('pet_cliente_cadastro/<int:id_PetCliente>/',
         views.fnctn_pet_clnte_cdstro, name="url_pet_clnte_cdstro"),

    path('pet_cliente_cdstr_Add/<int:id_Cliente>/',
         views.fnctn_pet_clnte_add, name="url_pet_clnte_add"),

    path('exames/', views.fnctn_pcnts_exmes, name="url_pcnts_exmes"),
    path('exame/<int:id_exame>/', views.fnctn_pcnts_exme, name="url_pcnts_exme"),
    path('minhas_autoriza/', views.fnctn_mnhs_atrza, name="url_mnhs_atrza"),
    path('autorizacoes/', views.fnctn_atrzacoes, name="url_atrzacoes"),
    path('autorizacao/<int:id_Ntfccao>/<int:id_consulta>/',
         views.fnctn_atrzacao, name="url_atrzacao"),
    path('salvar_notificacao/', views.fnctn_slvr_ntfccao,
         name='url_salvar_notificacao'),
    path('atualizaautorizacao/<int:id_Ntfccao>/<int:id_consulta>/',
         views.fnctn_atlza_atrzacao, name="url_atlza_atrzacao"),
    path('add_autorizacao/<int:id_consulta>/',
         views.fnctn_add_atrzacao, name="url_add_atrzacao"),
    path('envia_whtsapp_ntficacao/<int:id_Ntfccao>/',
         views.fnctn_envia_whtsapp_ntficacao, name="url_envia_whtsapp_ntficacao"),
    path('envia_email_ntficacao/<int:id_Ntfccao>/',
         views.fnctn_envia_email_ntficacao, name="url_envia_email_ntficacao"),
    path('atrzcao_rspsta/', views.fnctn_atrzcao_rspsta, name="url_atrzcao_rspsta"),


]

paciente/models.py
from django.db import models
from django.contrib.auth.models import User
from medico.models import DatasAbertas, DadosMedico
import datetime


from datetime import date


def calcular_idade(dt_nascimento):
    if not dt_nascimento:
        return "Data de nascimento não informada"

    hoje = date.today()
    anos = hoje.year - dt_nascimento.year
    meses = hoje.month - dt_nascimento.month

    # Ajustar caso os meses sejam negativos
    if meses < 0:
        anos -= 1
        meses += 12

    return f"{anos} anos e {meses} meses"


class Pet(models.Model):
    Pet = models.CharField(max_length=50)

    def __str__(self):
        return self.Pet


# ----------------------------------------------------------------------------------------------
# Definindo a Classe de Pet´s do Cliente
class Pet_Cliente(models.Model):
    status_petcliente = (
        ('A', 'Ativo'),
        ('I', 'Inativo')
    )
    cliente = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    Pet = models.ForeignKey(
        Pet, on_delete=models.DO_NOTHING, null=True, blank=True)
    Pet_Raca = models.CharField(max_length=140, null=True, blank=True)
    Pet_Pelagem = models.CharField(max_length=150, null=True, blank=True)
    Pet_Nome = models.CharField(max_length=140, null=True, blank=True)
    Pet_Sexo_Id = (
        ('I', 'Indefindio'),
        ('M', 'Macho'),
        ('F', 'Femea')
    )
    Pet_Sexo = models.CharField(max_length=1, choices=Pet_Sexo_Id, default='I')
    Pet_Foto = models.ImageField(upload_to="fotos_pet", null=True, blank=True)
    status = models.CharField(
        max_length=1, choices=status_petcliente, default='A')
    dt_Nscmnto = models.DateField(null=True, blank=True)  # Data de Nascimento

    def __str__(self):
        return self.cliente.username


class Consulta(models.Model):
    status_choices = (
        ('A', 'Agendada'),
        ('F', 'Finalizada'),
        ('C', 'Cancelada'),
        ('L', 'Avaliada'),
        ('I', 'Iniciada')
    )
    paciente = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    Medico = models.ForeignKey(
        DadosMedico, on_delete=models.DO_NOTHING, null=True, blank=True)
    Pet_Cliente = models.ForeignKey(
        Pet_Cliente, on_delete=models.DO_NOTHING, null=True, blank=True)
    data_aberta = models.ForeignKey(DatasAbertas, on_delete=models.DO_NOTHING)
    status = models.CharField(
        max_length=1, choices=status_choices, default='A')
    link = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.paciente.username


class Documento(models.Model):
    consulta = models.ForeignKey(Consulta, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=30)
    documento = models.FileField(upload_to='documentos')

    def __str__(self):
        return self.titulo

# -------------------------------------------------------------------------------------------
# Definindo a classe de Notificações, tabela que armazena as notificações geradas


class Notificacao(models.Model):
    consulta = models.ForeignKey(Consulta, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=200)
    descricao = models.TextField(null=True, blank=True)
    NmroWhtsApp = models.CharField(max_length=30, null=True, blank=True)
    token = models.CharField(max_length=150, default='SOME STRING')
    dt_envio = models.DateTimeField(
        default=datetime.datetime.now)  # Data do Envio
    ip_rspsta = models.CharField(max_length=15, default='SOME STRING')
    rspsta_grpo = (
        ('0', 'Não Aprovado'),
        ('2', 'Aprovado'),
        ('3', 'Indefinido')
    )
    rspsta = models.CharField(max_length=1, choices=rspsta_grpo, default='3')
    dt_rspsta = models.DateTimeField(null=True, blank=True)  # Data da Resposta

    def __str__(self):
        return self.NmroWhtsApp

paciente/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.messages import constants
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.utils.timezone import now, make_aware, localtime
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.db.models import Count, DateTimeField


from medico.models import DadosMedico, Especialidades, DatasAbertas, is_medico, Exames
from usuarios.models import is_Gerente, is_Atendente, is_Médico, is_Cliente, Get_cGrp_Usuario, Perfil
from usuarios.utilities import clclar_idade
from usuarios.models import Prfl_Endereco
from security.models import Security_Logs
from .models import Consulta, Documento, Notificacao, Pet_Cliente, Pet, calcular_idade
from datetime import datetime, timedelta
from collections import defaultdict

import smtplib
import email.message

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
import time


import time
import uuid
import urllib
import os

# ----------------------------------------------------------------------------------------------------------
# # Acessando a página inicial do sistema


@login_required(login_url='/usuarios/login/')
def home(request):

    Get_IS_GERENTE = is_Gerente(request.user)
    Get_IS_ATENDENTE = is_Atendente(request.user)
    Get_IS_MEDICO = is_Médico(request.user)
    Get_IS_CLIENTE = is_Cliente(request.user)

    if request.method == "GET":
        medico_filtrar = request.GET.get('seek_medico')
        especialidades_filtrar = request.GET.getlist('seek_espcldds')

        slct_medicos = DadosMedico.objects.all()
        dados_medicos = DadosMedico.objects.all()
        if medico_filtrar:
            slct_medicos = slct_medicos.filter(nome__icontains=medico_filtrar)

        if especialidades_filtrar:
            slct_medicos = slct_medicos.filter(
                especialidade_id__in=especialidades_filtrar)

        # Seleção das Atividades por cidades. Usado no Gráfico tipo 'radar'.
        hoje = datetime.now().date()
        mes_extenso = hoje.strftime('%B').capitalize()  # exemplo: 'Setembro'
        mesAnoCrrnte = f"{mes_extenso} {hoje.year}"
        data_inicio = make_aware(datetime.combine(hoje, datetime.min.time())).replace(
            microsecond=0).astimezone(None).replace(tzinfo=None)
        data_fim = make_aware(datetime.combine(hoje, datetime.max.time())).replace(
            microsecond=0).astimezone(None).replace(tzinfo=None)

        # Filtra pelo período desejado
        dados = (
            Security_Logs.objects
            .filter(DtHr_Atividade__range=(data_inicio, data_fim))
            .values('Cidade', 'Atividade')
            .annotate(total=Count('id'))
        )

        # Cria listas
        atividades = sorted(set(d['Atividade'] for d in dados))
        cidades = sorted(set(d['Cidade'] for d in dados))

        # Calcula o valor máximo de cada atividade
        max_por_atividade = defaultdict(int)
        for d in dados:
            if d['total'] > max_por_atividade[d['Atividade']]:
                max_por_atividade[d['Atividade']] = d['total']

        slct_Cidades = (
            Security_Logs.objects.filter(
                DtHr_Atividade__range=(data_inicio, data_fim))
            # Retorna só os nomes das cidades
            .values_list('Cidade', flat=True)
            .distinct()                        # Remove duplicadas
            # Ordena alfabeticamente
            .order_by('Cidade')
        )
        # Monta estrutura para o gráfico pizza
        sries_dta_Atvddes = []
        for atividade in atividades:
            registro = next(
                (r for r in dados if r['Atividade'] == atividade), None)
            vlres_atvdde = registro['total'] if registro else 0
            sries_dta_Atvddes.append(
                {'atvddeValor': vlres_atvdde * 100, 'atvddeNome': atividade})

        # Monta estrutura para o gráfico radar
        series_data = []
        for cidade in cidades:
            valores = []
            for atividade in atividades:
                registro = next(
                    (r for r in dados if r['Cidade'] == cidade and r['Atividade'] == atividade), None)
                valores.append(registro['total'] if registro else 0)
            series_data.append({'value': valores, 'name': cidade})

        slct_espcldds = Especialidades.objects.all()
        return render(request, 'home.html', {'cGrp_Usuario': Get_cGrp_Usuario(request.user),
                                             'IS_GERENTE': Get_IS_GERENTE,
                                             'IS_ATENDENTE': Get_IS_ATENDENTE,
                                             'IS_CLIENTE': Get_IS_CLIENTE,
                                             'IS_MEDICO': Get_IS_MEDICO,
                                             'dados_medicos': dados_medicos,
                                             'Rgstrs_MaxAtvddes': [max_por_atividade[a] for a in atividades],
                                             'medicos': slct_medicos,
                                             'mesAnoCorrente': mesAnoCrrnte,
                                             'Rgstrs_Atvddes': sries_dta_Atvddes,
                                             'Rgstrs_Cddes': slct_Cidades,
                                             'Rgstrs_Series': series_data,
                                             'especialidades': slct_espcldds,
                                             'is_medico': is_medico(request.user)})


def obter_ip_cliente(request):
    ip = request.META.get('HTTP_X_FORWARDED_FOR')
    if ip:
        ip = ip.split(',')[0]  # Se houver múltiplos IPs, pega o primeiro

    else:
        ip = request.META.get('REMOTE_ADDR')  # IP direto do cliente

    return ip


def fnctn_esclhr_hrrio(request, id_dados_medicos):
    if request.method == "GET":
        slct_medico = DadosMedico.objects.get(id=id_dados_medicos)
        slct_dts_abertas = DatasAbertas.objects.filter(user=slct_medico.user).filter(
            data__gte=datetime.now()).filter(agendado=False)
        return render(request, 'escolher_horario.html', {'medico': slct_medico, 'datas_abertas': slct_dts_abertas, 'is_medico': is_medico(request.user)})


def fnctn_agndr_hrrio(request, id_data_aberta):
    if request.method == "GET":
        data_aberta = DatasAbertas.objects.get(id=id_data_aberta)

        horario_agendado = Consulta(
            paciente=request.user,
            data_aberta=data_aberta
        )

        horario_agendado.save()

        # TODO: Sugestão Tornar atomico

        data_aberta.agendado = True
        data_aberta.save()

        messages.add_message(request, constants.SUCCESS,
                             'Horário agendado com sucesso.')

        return redirect('/pacientes/minhas_consultas/')


def fnctn_mnhs_cnslts(request):
    if request.method == "GET":
        # TODO: desenvolver filtros

        # Consultas de hoje
        # slct_mnhs_cnslts = Consulta.objects.filter(paciente=request.user).filter(data_aberta__data__gte=datetime.now())

        # Todas as consultas do Clientex
        slct_mnhs_cnslts = Consulta.objects.filter(paciente=request.user)

        return render(request, 'minhas_consultas.html', {'minhas_consultas': slct_mnhs_cnslts, 'cGrp_Usuario': Get_cGrp_Usuario(request.user), 'is_medico': is_medico(request.user)})


def fnctn_cnslta(request, id_consulta):
    if request.method == 'GET':
        # slct_cnslta = Consulta.objects.get(id=id_consulta)
        slct_cnslta = get_object_or_404(Consulta, id=id_consulta)
        slct_ddo_mdco = DadosMedico.objects.get(user=slct_cnslta.Medico.user)
        slct_dcmnts = Documento.objects.filter(consulta=id_consulta)
        slct_ntficcoes = Notificacao.objects.filter(consulta=id_consulta)
        slct_id_Perfil = Perfil.objects.get(user=slct_cnslta.paciente)

        slct_Pet_Consulta = Pet_Cliente.objects.get(
            id=slct_cnslta.Pet_Cliente.id)

        # Conta todas as notificações com resposta igual a Indefinido (3).
        slct_TF_add_ntfcacs = Notificacao.objects.filter(
            consulta=id_consulta).filter(rspsta=3).count()

        slct_Pet_Sxos = list(Pet_Cliente.Pet_Sexo_Id)
        slct_Get_Pet = Pet.objects.all().order_by('Pet')

        return render(request, 'consulta.html', {'ntficcoes': slct_ntficcoes,
                                                 'perfil': slct_id_Perfil,
                                                 'lAddNtfccs': slct_TF_add_ntfcacs,
                                                 'consulta': slct_cnslta,
                                                 'cGrp_Usuario': Get_cGrp_Usuario(request.user),
                                                 'Lst_Pets': slct_Get_Pet,
                                                 'Lst_Pts_Sxo': slct_Pet_Sxos,
                                                 'documentos': slct_dcmnts,
                                                 'pet_Consulta': slct_Pet_Consulta,
                                                 'dado_medico': slct_ddo_mdco,
                                                 'is_medico': is_medico(request.user)
                                                 }
                      )


# Lista todas as consultas, de todos os clientes, para que possa atribuir uma notificação de autorização a essa consulta.
def fnctn_atrzacoes(request):
    if request.method == "GET":
        slct_Ntfccoes = Notificacao.objects.all()

paciente/templates/consulta.html
{% extends "base.html" %}
{% load static %}
<!doctype html>
<html lang="pt-BR">


{% block 'head' %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/5.0.8/inputmask.min.js"></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">


{% endblock 'head' %}

{% block 'body' %}

    <main id="main" class="main">
  
        <div class="row">

            <div class="pagetitle">
                <h1>Consulta Selecionada</h1>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'url_home' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'url_pcnts_cnsltas' %}">Cadastro</a></li>
                    <li class="breadcrumb-item active">Consulta</li>
                </ol>
            </div>


            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-2"><img src="{{perfil.Foto.url}}" class="rounded-circle" style="height: auto; max-width: 255px;" alt="Foto do Cliente"></div>
                    <div class="col-md">
                        <p class="p-bold"><a><b>.Cliente: </b>{{consulta.paciente.first_name}} {{consulta.paciente.last_name}}</a>
                        <p><b>Endereço: </b>{{ perfil.Endereco }} - {{ perfil.Cidade }}/{{ perfil.UF }}</p>
                        <p title="{{dado_medico.descricao}}"><b>Médico:</b> {{dado_medico.nome}} - {{dado_medico.descricao}}</p>
                        <p><b>Data da Consulta: </b>{{consulta.data_aberta.data}}</p>
                    </div>
                </div>

                <hr>
                <br>
                <div class="row">
                    <div class="col-md">
                        <p><i class="color-dark bi bi-check-circle-fill"></i> Consulta Agendada</p>
                    </div>
                    <div class="col-md">
                        <p><i class="{% if consulta.status == 'F' or consulta.status == 'L' %}color-dark{% endif %} 
                                        bi bi-check-circle-fill">
                            </i> Consulta Realizada
                        </p>
                    </div>
                    <div class="col-md">
                        <p><i class="{% if consulta.status == 'L' %}color-dark{% endif %} bi bi-check-circle-fill"></i> Consulta Avaliada</p>
                    </div>
                </div>
                <hr> 
                <h3 class="p-bold">Detalhes da consulta</h3>
                <div class="row mb-12">
                   
                   
                   
                    <div class="col-md-2">
                        <img src="{{pet_Consulta.Pet_Foto.url}}" class="foto-perfil-card-lg" style="height: auto; width: 200px;" title="Foto do Pet" alt="Foto do Pet">
                    </div>
                   
                    <div class="col-sm-2">
                        <div data-mdb-input-init class="form-outline">
                            <label for="">Espécie:</label>
                                <select name="get_Pet_Especie" disabled class="form-control shadow-main-color form-select" >
                                    {% for Pet_Slct in Lst_Pets %}
                                        <option {% if Pet_Slct.id == pet_Consulta.Pet_id %} selected {% endif %} value="{{ Pet_Slct.id }}">{{ Pet_Slct.Pet }}</option>
                                    {% endfor %}
                                </select><br>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div data-mdb-input-init class="form-outline">
                            <label for="">Raça:</label>
                            <input type="text" class="form-control shadow-main-color" disabled name="get_Pet_Raca" value="{{pet_Consulta.Pet_Raca}}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div data-mdb-input-init class="form-outline">
                            <label for="">Nome:</label>
                            <input type="text" class="form-control shadow-main-color" disabled name="get_Pet_Nome" value="{{pet_Consulta.Pet_Nome}}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div data-mdb-input-init class="form-outline">
                            <label for="">Sexo:</label>
                                <select  name="get_Pet_Sexo" id="id_Pet_Sexo" disabled class="form-control shadow-main-color form-select" >
                                    {% for valor, nome in Lst_Pts_Sxo %}
                                        <option {% if valor == pet_Consulta.Pet_Sexo %} selected {% endif %} value="{{ valor }}">{{ nome }}</option>
                                    {% endfor %}
                                </select>
                                <br>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div data-mdb-input-init class="form-outline">
                            <label for="">dt Nascimento:</label>
                            <input type="text" class="form-control shadow-main-color" disabled maxlength="10" placeholder="DD/MM/YYYY" required name="get_Pet_dtNscmnto" value="{{pet_Consulta.dt_Nscmnto | date:"d/m/Y"}}">
                            <p id="mensagem"></p>
                        </div>
                    </div>
                </div>
                
                <hr>
                <h3 class="p-bold">Documentos</h3>
                <br>

                {% for documento in documentos %}
                    <a href="{{documento.documento.url}}" target="_OpenDocumento" class="link documentos"><i class="bi bi-file-arrow-down"></i> {{documento.titulo}} - {{documento.consulta.data_aberta.data.year}}</a>
                    <br><br><br>
                {% endfor %}
   
                <br>
                <hr>
                <h3 class="p-bold">Notificações/Aprovações</h3>
                <div class="list-minhas-consultas" >
                    <table class="table table-success table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Titulo</th>
                                <th scope="col">Data de Envio</th>
                                <th scope="col">Resposta</th>
                                <th scope="col">Ação</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ntficcao in ntficcoes %}
                                <tr>
                                    <td><a href="{% url 'url_atrzacao' ntficcao.id  consulta.id %}">{{ntficcao.titulo}}</a></td>
                                    <td><a href="{% url 'url_atrzacao' ntficcao.id  consulta.id %}">{{ntficcao.dt_envio|date:"d-m-Y"}}</a></td>
                                    <td><a href="{% url 'url_atrzacao' ntficcao.id  consulta.id %}">{{ntficcao.get_rspsta_display}}</a></td>
                                    <td><a title="Envia Notificação para aprovação" href="{% url 'url_atrzacao' ntficcao.id  consulta.id %}">Enviar Notificação</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if lAddNtfccs > 0  %}
                    <div class="row">
                        <div class="col-md">
                            <td>
                                <input type="submit" style="text-align:center; cursor:pointer; WIDTH:100%" title="Não é possível adicionar uma nova notificação, pois há notificação com resposta indefinida" disabled value="Não é possível adicionar uma nova notificação, pois há notificação com resposta indefinida. " class="btn btn-success btn-dark-color">
                            </td>
                        </div>
                    </div> 
                {% else %}
                    <form action="{% url 'url_add_atrzacao' consulta.id  %}" method="POST">{% csrf_token %}
                        <div class="row">
                            <div class="col-md">
                                <td>
                                    <input type="submit"  style="text-align:center; cursor:pointer; WIDTH:100%" title="Adiciona uma nova notificação para aprovação do cliente." value="Adiciona uma nova notificação para a consulta acima, para aprovação do cliente. " class="btn btn-success btn-dark-color">
                                </td>
                            </div>
                        </div> 
                    </form>
                {% endif %}
            </div>
        </div>
        
    </main>

    <!--Ativa as opções do menu principal esquerdo -->
<script language="JavaScript">
    <!--
        document.getElementById('components-nav').className ='nav-content collapse show';
        document.getElementById('sidebar-nav-Atendimento-consultas').className ='active';
    //-->
</script>


{% endblock 'body' %}

paciente/templates/notificacao_rspsta.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}

    <link rel="stylesheet" href="{% static 'medicos/css/abrir_horario.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'medicos/css/cadastro_medico.css' %}">
    <link rel="stylesheet" href="{% static 'pacientes/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'pacientes/css/agendar_horario.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

{% endblock 'head' %}

{% block 'body' %}
    {% include "partials/navbar.html" %}

    <br><br>
    <div class="container">
        {% if atrzacao.rspsta == '0' %}
            <div class="alert alert-danger" role="alert">
                Autorização Não Aceita. Recusada.
            </div>
        {% elif atrzacao.status == '2' %}
            <div class="alert alert-success" role="alert">
                Autorização Aceita
            </div>
        {% elif atrzacao.status == '3' %}
            <div class="alert alert-primary" role="alert">
                Autorização Enviada, aguardando decisão do cliente
            </div>
        {% endif %}    
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md">
                        <p style="font-size: 20px" class="p-bold">Cliente:</p>
                        <p style="font-size: 18px">{{consulta.paciente.first_name}} {{consulta.paciente.last_name}}<br>
                        {{ perfil.Endereco }}
                        </p>
                        <p title="{{dado_medico.descricao}}"><b>Médico:</b> {{dado_medico.nome}}</p>
                        <p><b>Data do Exame: </b>{{consulta.data_aberta.data |date:"d-m-Y"}}</p>
                        <p><b>Status: </b>{{ consulta.get_status_display }}</p>
                    </div>
                </div> 
                <hr>
                <h3 class="p-bold">Detalhes da Autorização</h3>
                    <p style="font-size: 20px" class="p-bold">Título:</p>
                    <p style="font-size: 18px">{{ atrzacao.titulo }}<br>
                    <p style="font-size: 20px" class="p-bold">dT Envio:</p>
                    <p style="font-size: 18px">{{ atrzacao.dt_envio }}<br>
                    <p style="font-size: 20px" class="p-bold">Descricao:</p>
                    <p style="font-size: 18px">{{ atrzacao.descricao }}<br>
                    <p style="font-size: 20px" class="p-bold">Resposta:</p>
                    <p style="font-size: 18px">{{ atrzacao.get_rspsta_display }}<br>
                <hr>
                <br>
                <form action="{% url 'url_envia_email_ntficacao' id_Ntfccao %}" method="POST">{% csrf_token %}
                    <div class="row">
                        <div class="col-md">
                            <td>
                                <input type="submit" title="Envia Notificação para aprovação" value="Enviar eMail desta notificação para aprovação do cliente." class="btn btn-success btn-dark-color">
                            </td>
                        </div>
                    </div> 
                </form>
            </div>
            <div class="col-md"></div>
        </div>
        
    </div>

{% endblock 'body' %}